### ISSUE TITLE
安卓里的webview判断还是false

### ISSUE THREAD

**Issue by LLLiuRX** [wuliqiangqiang/is-webview#2]

**Comment by wuliqiangqiang** [comment]
@LLLiuRX 抱歉，这个包可能兼容不到那么多设备了，很久没维护到

**Comment by iDestin** [comment]
@LLLiuRX 我用这个库也不行，发现了一个新的库 [is-ua-webview](https://www.npmjs.com/package/is-ua-webview) 可以试试，安卓没问题

**Comment by LLLiuRX** [comment]
> @LLLiuRX 我用这个库也不行，发现了一个新的库 [is-ua-webview](https://www.npmjs.com/package/is-ua-webview) 可以试试，安卓没问题

好的 谢谢
